import type { Metadata } from 'next';
import '@/shared/styles/globals.css';
import Footer from '@/shared/components/footer';
import { NavMenu } from '@/shared/components/navbar';
export const metadata: Metadata = {
  title: 'Shoppet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavMenu />
      {children}
      <Footer />
    </>
  );
}
