import type { Metadata } from 'next';
import { Geist_Mono, Sora } from 'next/font/google';
import '@/shared/styles/globals.css';
import { NavMenu } from '@/shared/components/navbar';

const sora = Sora({
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Shoppet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavMenu />
      {children}
    </>
  );
}
