import { SidebarProvider } from '@/shared/components/ui/sidebar';
import type { Metadata } from 'next';
import SidebarDashboard from './page';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="block md:flex h-screen">
        <div className="block sm:flex ">
          <SidebarDashboard />
        </div>
        <div className="flex-1 min-h-screen bg-background">
          <main className="h-full w-full p-6 overflow-y-auto">{children}</main>
        </div>
      </div>
    </SidebarProvider>
  );
}
