import SidebarDashboard from '@/shared/components/sidebar';
import { SidebarProvider } from '@/shared/components/ui/sidebar';
import { ThemeSwitcher } from '@/shared/components/ui/theme-switcher';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="block md:flex h-screen relative">
        <div className="absolute hidden md:block top-5 right-5 z-50">
          <ThemeSwitcher />
        </div>
        <div className="block sm:flex relative z-[9999]">
          <SidebarDashboard />
        </div>
        <div className="flex-1 min-h-screen bg-background relative z-0">
          <main className="h-full w-full p-6 overflow-y-auto">{children}</main>
        </div>
      </div>
    </SidebarProvider>
  );
}
